### ISSUE TITLE
Use HTTP 503 for strike page

### ISSUE THREAD

**Issue by sebastiangreger** [iamwebrocker/wp-climatestrike#2]
Great to see this WP port! ...you beat me to it :) As I had already been researching on how to achieve that in WP, and just in case you'd like to go down the HTTP 503 path as well:

- `wp_redirect($strike_url, 503)`, which I first assumed to be the solution would not work. It correctly returns the HTTP code, but not the HTML.

- `status_header(503)`, followed by echoing the strike page content returns the HTML while leaving the URL unaltered in the browser. That's the equivalent to what I did with Kirby.

PS: I like the idea of looking for a custom template in the default template folder - will shamelessly copy that ;)

**Comment by iamwebrocker** [comment]
Ah, thank you.
I went with the wp_redirect(....,503) option, but this returned a blank page, so I settled for the "normal" redirect. My first version had a `header('location:....,503)` thing.
Will try your suggestion with the status_header. :-)

**Comment by iamwebrocker** [comment]
Nice!! This works like a charm, will push a new version soon.
